# Generated by Django 4.2 on 2023-07-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['id'], 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
    ]
