# Generated by Django 4.2 on 2023-05-21 17:06

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_icecreammarket_parent_spare_alter_bb_options_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='percent',
            field=models.IntegerField(blank=True, null=True, validators=[bboard.models.get_positive_numbers], verbose_name='Процент'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[bboard.models.get_positive_numbers], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='taste',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Вкус'),
        ),
    ]
