# Generated by Django 4.2 on 2023-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_icecream_percent_icecream_price_alter_icecream_taste'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecreammarket',
            name='color',
            field=models.CharField(choices=[('b', 'black'), ('w', 'white')], default='b', max_length=1),
        ),
    ]
