# Generated by Django 4.2 on 2023-10-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Задача')),
                ('notes', models.CharField(max_length=255, verbose_name='Описание')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Лист задач',
                'verbose_name_plural': 'Лист задач',
                'ordering': ['start'],
            },
        ),
    ]
