# Generated by Django 4.2 on 2023-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['start'], 'verbose_name': 'Лист задач', 'verbose_name_plural': 'Лист задач'},
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало'),
        ),
    ]
