# Generated by Django 4.2 on 2023-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksheet', '0002_alter_task_options_alter_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
    ]
